import { NextRequest, NextResponse } from "next/server";

import {
  attachSpotifyAuthCookies,
  getRequestSpotifyTokens,
  refreshSpotifyAccessToken,
} from "@/lib/spotify-auth";
import {
  addTracksToPlaylist,
  createPlaylist,
  getCurrentUserProfile,
} from "@/lib/spotify-api";

type CreatePlaylistBody = {
  name?: string;
  description?: string;
  trackUris?: string[];
};

async function createOnSpotify(accessToken: string, body: CreatePlaylistBody) {
  const profile = await getCurrentUserProfile(accessToken);

  const playlist = await createPlaylist(
    accessToken,
    profile.id,
    body.name ?? "MTN DEW Custom Mix",
    body.description ?? "Generated by OpenDew Sommelier",
  );

  const uris = (body.trackUris ?? []).filter((uri) => uri.startsWith("spotify:track:"));
  if (uris.length > 0) {
    await addTracksToPlaylist(accessToken, playlist.id, uris);
  }

  return playlist;
}

export async function POST(request: NextRequest) {
  const { accessToken, refreshToken } = getRequestSpotifyTokens(request);
  const body = (await request.json()) as CreatePlaylistBody;

  if (!accessToken) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  try {
    const playlist = await createOnSpotify(accessToken, body);
    return NextResponse.json({
      id: playlist.id,
      url: playlist.external_urls.spotify,
    });
  } catch {
    if (!refreshToken) {
      return NextResponse.json({ error: "Session expired" }, { status: 401 });
    }

    try {
      const tokens = await refreshSpotifyAccessToken(refreshToken);
      const playlist = await createOnSpotify(tokens.access_token, body);
      const response = NextResponse.json({
        id: playlist.id,
        url: playlist.external_urls.spotify,
      });
      attachSpotifyAuthCookies(response, {
        ...tokens,
        refresh_token: tokens.refresh_token ?? refreshToken,
      });
      return response;
    } catch {
      return NextResponse.json(
        { error: "Failed to create Spotify playlist" },
        { status: 500 },
      );
    }
  }
}
