import { NextRequest, NextResponse } from "next/server";

import {
  attachSpotifyAuthCookies,
  clearSpotifyAuthCookies,
  getRequestSpotifyTokens,
  isRefreshTokenRevokedError,
  refreshSpotifyAccessToken,
} from "@/lib/spotify-auth";
import {
  addTracksToPlaylist,
  createPlaylist,
} from "@/lib/spotify-api";

type CreatePlaylistBody = {
  name?: string;
  description?: string;
  trackUris?: string[];
};

async function createOnSpotify(accessToken: string, body: CreatePlaylistBody) {
  const playlist = await createPlaylist(
    accessToken,
    body.name ?? "MTN DEW Custom Mix",
    body.description ?? "Generated by OpenDew Sommelier",
  );

  const uris = (body.trackUris ?? []).filter((uri) => uri.startsWith("spotify:track:"));
  let trackSummary = { requested: 0, added: 0, skipped: 0 };
  if (uris.length > 0) {
    trackSummary = await addTracksToPlaylist(accessToken, playlist.id, uris);
  }

  return { playlist, trackSummary };
}

export async function POST(request: NextRequest) {
  const { accessToken, refreshToken } = getRequestSpotifyTokens(request);
  const body = (await request.json().catch(() => ({}))) as CreatePlaylistBody;

  if (!accessToken) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  try {
    const result = await createOnSpotify(accessToken, body);
    return NextResponse.json({
      id: result.playlist.id,
      url: result.playlist.external_urls.spotify,
      trackSummary: result.trackSummary,
    });
  } catch (firstError) {
    if (!refreshToken) {
      const message =
        firstError instanceof Error ? firstError.message : "Session expired";
      return NextResponse.json({ error: message }, { status: 401 });
    }

    try {
      const tokens = await refreshSpotifyAccessToken(refreshToken);
      const result = await createOnSpotify(tokens.access_token, body);
      const response = NextResponse.json({
        id: result.playlist.id,
        url: result.playlist.external_urls.spotify,
        trackSummary: result.trackSummary,
      });
      attachSpotifyAuthCookies(response, {
        ...tokens,
        refresh_token: tokens.refresh_token ?? refreshToken,
      });
      return response;
    } catch (secondError) {
      if (isRefreshTokenRevokedError(secondError)) {
        const response = NextResponse.json(
          { error: "Spotify session expired. Please reconnect Spotify." },
          { status: 401 },
        );
        clearSpotifyAuthCookies(response);
        return response;
      }

      const message =
        secondError instanceof Error
          ? secondError.message
          : "Failed to create Spotify playlist";
      return NextResponse.json(
        { error: message },
        { status: 500 },
      );
    }
  }
}
